### PR TITLE
feat: Support for .NET 7 ARM64 container builds

### PR DESCRIPTION
**Pull request by mrkdeng**
*Issue #, if available:*
This PR contains changes that complete support for .NET 7 container builds #68 #69 by adding support for ARM64 container builds.
  
*Description of changes:*
Currently the .NET 7 SAM build images only support x86_64 because .NET 7 was previously not compatible with AL2 on ARM. Microsoft reduced the dependencies needed for .NET 7 ARM, and now we can build ARM support for .NET 7.
This PR contains code changes to take architecture argument and build ARM64 image for .NET 7.

.NET 7 Lambda arm64 base image is now available on https://gallery.ecr.aws/lambda/dotnet

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by lucashuy — APPROVED** [review]

**Review by mndeveci — APPROVED** [review]
Changes looks good to me, anything that we need to change in SAM CLI @mrkdeng ?

**Comment by mrkdeng** [comment]
@lucashuy @mndeveci Thank you for reviewing this PR. We didn't include any arch specific change in previous PRs, so I don't think we need to change anything in SAM CLI.

**Comment by mndeveci** [comment]
> @lucashuy @mndeveci Thank you for reviewing this PR. We didn't include any arch specific change in previous PRs, so I don't think we need to change anything in SAM CLI.

Thanks for your reply, before we move forward can you locally build this image and test it withing SAM CLI with arm64 target runtime?

**Comment by mrkdeng** [comment]
> > @lucashuy @mndeveci Thank you for reviewing this PR. We didn't include any arch specific change in previous PRs, so I don't think we need to change anything in SAM CLI.
> 
> Thanks for your reply, before we move forward can you locally build this image and test it withing SAM CLI with arm64 target runtime?

Yes. We built local image and tested .NET7 NativeAOT and non NativeAOT cases on M1 Mac (arm64), both worked fine.

**Review by philasmar — APPROVED** [review]

**Review by mndeveci — APPROVED** [review]

**Review by sriram-mv — APPROVED** [review]

**Review by hawflau — APPROVED** [review]

**Pull request merged**
