### PR TITLE
Update go example

### PR DESCRIPTION
**Pull request by mirpo**
*Issue #, if available:*
N/A

*Description of changes:*
- Update go to `1.18` in `go.mod`
- Update aws-lambda-go to the latest `v1.28.0`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

One more small update related to `go 1.18`

### CODE REVIEW

**Review by mndeveci — APPROVED** [review]

**Review by hoffa — APPROVED** [review]

**Comment by hoffa** [comment]
Thank you! 🙏

**Comment by mirpo** [comment]
@hoffa A little off topic, could you please find internally who can help us with this PR https://github.com/aws/aws-codebuild-docker-images/pull/519? Thanks in advance!

**Comment by hoffa** [comment]
@mirpo I've pinged the relevant team.

**Comment by mirpo** [comment]
thanks a lot!

**Pull request merged**
